---
title: "Macro Simulation (Caiani et. al., 2016)"
author: "Sérgio Rivero"
date: "`r Sys.time()`"
output:
  html_document:
    df_print: paged
  pdf_document: default

---



```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE, eval = TRUE)

### Generating the simulation Results
rm(list=ls())
```



```{r loadLibs}

### Getting the Libraries
library(tidyverse)

```


```{r setupDirs}

### Setting up the Directories
i  <-  "../runs"
o  <-  "../results"
```



```{r getFiles, eval=TRUE}

### Getting the files 
csv_files <- fs::dir_ls(i, regexp = "macro_model*")

```



```{r generatingDF, eval=TRUE}

### Generating runs dataframe



model_runs  <- csv_files %>%
    map_dfr(read_csv)

model_runs <- model_runs[complete.cases(model_runs),]

```


## Results


```{r}
## Agregate all variables by step getting the mean of all numerical variables

aggregated_data <- model_runs %>%
  group_by(step) %>%
  summarise(across(where(is.numeric), mean))

```


