---
title: "Macro Simulation (Caiani et. al., 2016)"
author: "Sérgio Rivero"
date: "`r Sys.time()`"
output:
  html_document:
    df_print: paged
  pdf_document: default

---



```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE, eval = TRUE)

### Generating the simulation Results
rm(list=ls())
```



```{r loadLibs}

### Getting the Libraries
library(tidyverse)

```


```{r setupDirs}

### Setting up the Directories
i  <-  "../runs"
o  <-  "../results"
```



```{r getFiles, eval=TRUE}

### Getting the files 
files <- list.files(path = i, pattern = "macro_model_Household")
Household <- read.csv(file.path(i, files)) %>%
  select(-c(run, index_no))

files <- list.files(path = i, pattern = "macro_model_CGFirm")
CGFirm <- read.csv(file.path(i, files)) %>%
  select(-c(run, index_no))




```



```{r generatingDFs, eval=FALSE}


#household_means <- Household %>%
#  group_by(step) %>%
#  summarise(across(where(is.numeric), mean))



#cg_means <- CGFirm %>%
#  group_by(step) %>%
#  summarise(across(where(is.numeric), mean))
```




```{r, eval=FALSE}


#household_means <- Household %>%
#  group_by(step) %>%
#  summarise(across(where(is.numeric), mean),
#            across(where(is.logical), sum))

#cg_means <- CGFirm %>%
#  group_by(step) %>%
#  summarise(across(where(is.numeric), mean),
#            across(where(is.logical), sum))
```


```{r}
household_means <- Household %>%
  group_by(step) %>%
  summarise(across(where(is.numeric), mean),
            across(where(is.logical), ~ sum(.x, na.rm = TRUE), .names = "count_{.col}"))

cg_means <- CGFirm %>%
  group_by(step) %>%
  summarise(across(where(is.numeric), mean),
            across(where(is.logical), ~ sum(.x, na.rm = TRUE), .names = "count_{.col}"))
```
## Results



### Household

```{r}
# Generate multiple graphs for household *dataframe
library(gridExtra)
graphs <- map(names(household_means)[-1], function(var) {
  ggplot(household_means, aes(x = step, y = !!sym(var))) +
    geom_line() +
    labs(x = "Step", y = paste("means - ", var)) +
    ggtitle(paste("Household -", var)) +
    theme(
      plot.title = element_text(size = 10),
      axis.title = element_text(size = 8)
    )
})

graphs <- map(names(household_means)[-1], function(var) {
  ggplot(household_means, aes(x = step, y = !!sym(var))) +
    geom_line() +
    labs(x = "Step", y = paste("means - ", var)) +
    ggtitle(paste("Household -", var))+
    theme(
      plot.title = element_text(size = 10),
      axis.title = element_text(size = 8)
    )
})

# Arrange the graphs in a grid with 3 graphs per row
do.call("grid.arrange", c(graphs, ncol = 4))

# Print the graphs
#print(graphs)
```


### Consumer Goods Firms


```{r}
# Generate multiple graphs for cg_means dataframe
graphs <- map(names(cg_means)[-1], function(var) {
  ggplot(cg_means, aes(x = step, y = !!sym(var))) +
    geom_line() +
    labs(x = "Step", y = paste("means - ", var)) +
    ggtitle(paste("CGFirm -", var))+
    theme(
      plot.title = element_text(size = 10),
      axis.title = element_text(size = 8)
    )
})


do.call("grid.arrange", c(graphs, ncol = 4))

# Print the graphs
#print(graphs)




```




```{r}
## Save the file
write.csv(household_means, file.path(o, "household_means.csv"), row.names = FALSE)

write.csv(cg_means, file.path(o, "cg_means.csv"), row.names = FALSE)
```